### ISSUE TITLE
change name of variable

### ISSUE THREAD

**Issue by annecori** [Hackout3/cleanr#3]
can we do that please?! thanks

**Comment by richfitz** [comment]
Can you remind me what we meant by this?  Was this an in-place rename only (deleting the old column?)

**Comment by annecori** [comment]
this was renaming the column, so keeping the same values in the column but changing the column name, without duplicating it, does that make sense?

**Comment by richfitz** [comment]
Yup, makes sense. This would be outside of the main `recode()` call, right?

**Comment by annecori** [comment]
I don't know - inside or outside - whatever you think makes more sense/is easier to code and to handle
